import { Inter, Fira_Mono, IBM_Plex_Sans_KR } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import Header from "../components/layout/Header"
import Footer from "../components/layout/Footer"
import { ThemeProvider } from "next-themes";
import { CategoryProvider } from "../context/category"
import { SearchTagProvider } from "../context/searchTag"
import { ServiceProvider } from "../context/ServiceContext"
import { POSTS_QUERY } from "../sanity/queries"
import { client } from "../sanity/client";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const firaMono = Fira_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-fira-mono",
});

const plexSans = IBM_Plex_Sans_KR({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-plex-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const posts = await client.fetch(POSTS_QUERY);

  return (
    <html
      lang="en"
      className={`${inter.variable} ${firaMono.variable} ${plexSans.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
      <ThemeProvider
        attribute="class"
        enableSystem
        defaultTheme="system"
      >
          <Header posts={posts} />
          <ServiceProvider>
            <SearchTagProvider>
              <CategoryProvider>
                {children}
              </CategoryProvider>
            </SearchTagProvider>
          </ServiceProvider>
        <Footer />
        <Toaster
          position="top-center"
          richColors
          toastOptions={{
            duration: 2500,
            classNames: {
              toast:
                "!rounded-full !px-5 !py-5 !border !border-white/30 !bg-white/20 !backdrop-blur-xl !shadow-[0_8px_30px_rgba(0,0,0,0.12)] !text-dark animate-toast-pop flex items-center justify-center",
              title: "!text-sm !font-semibold",
              description: "!text-xs !opacity-80",
            },
          }}
        />
      </ThemeProvider>
      </body>
    </html>
  );
}
