async function seedFeatures(prisma) {
  const features = [
    {
      name: "Responsive Design",
      koreanName: "반응형 디자인",
      minPriceDollar: 140,
      maxPriceDollar: 300,
      minPriceWon: 140000,
      maxPriceWon: 300000,
      minEstimatedDays: 1,
      maxEstimatedDays: 1,
      categories: [
        "Static Website Development",
        "Dynamic Website Development",
        "E-Commerce Development",
        "Admin Dashboard",
      ],
    },
    {
      name: "Mobile Optimization",
      koreanName: "모바일 최적화",
      minPriceDollar: 100,
      maxPriceDollar: 300,
      minPriceWon: 100000,
      maxPriceWon: 300000,
      minEstimatedDays: 1,
      maxEstimatedDays: 1,
      categories: [
        "Static Website Development",
        "Dynamic Website Development",
        "E-Commerce Development",
        "Admin Dashboard",
        "Conversion",
        "Website Maintenance",
      ],
    },
    {
      name: "Contact Form",
      koreanName: "문의 폼",
      minPriceDollar: 50,
      maxPriceDollar: 200,
      minPriceWon: 50000,
      maxPriceWon: 200000,
      minEstimatedDays: 1,
      maxEstimatedDays: 1,
      categories: [
        "Static Website Development",
        "Dynamic Website Development",
        "E-Commerce Development",
        "Website Maintenance",
      ],
    },
    {
      name: "Dark Mode",
      koreanName: "다크 모드",
      minPriceDollar: 50,
      maxPriceDollar: 100,
      minPriceWon: 50000,
      maxPriceWon: 100000,
      minEstimatedDays: 1,
      maxEstimatedDays: 1,
      categories: [
        "Static Website Development",
        "Dynamic Website Development",
        "E-Commerce Development",
        "Admin Dashboard",
        "Conversion",
        "Website Maintenance",
      ],
    },
    {
      name: "Page Animation",
      koreanName: "페이지 애니메이션",
      minPriceDollar: 50,
      maxPriceDollar: 200,
      minPriceWon: 50000,
      maxPriceWon: 200000,
      minEstimatedDays: 1,
      maxEstimatedDays: 1,
      categories: [
        "Static Website Development",
        "Dynamic Website Development",
        "E-Commerce Development",
        "Admin Dashboard",
        "Website Maintenance",
        "Branding & UI/UX",
      ],
    },
    {
      name: "Hosting Deployment",
      koreanName: "호스팅 배포",
      minPriceDollar: 50,
      maxPriceDollar: 200,
      minPriceWon: 50000,
      maxPriceWon: 200000,
      minEstimatedDays: 1,
      maxEstimatedDays: 1,
      categories: [
        "Static Website Development",
        "Dynamic Website Development",
        "CMS Development / Website Builder",
        "DevOps Services & Cloud Infrastructure",
        "Website Maintenance",
      ],
    },
    {
      name: "Multi-language Support",
      koreanName: "다국어 지원",
      minPriceDollar: 300,
      maxPriceDollar: 2000,
      minPriceWon: 300000,
      maxPriceWon: 2000000,
      minEstimatedDays: 1,
      maxEstimatedDays: 2,
      categories: [
        "Static Website Development",
        "Dynamic Website Development",
        "E-Commerce Development",
        "CMS Development / Website Builder",
        "SEO",
      ],
    },
    {
      name: "Additional Pages",
      koreanName: "페이지 추가",
      minPriceDollar: 120,
      maxPriceDollar: 300,
      minPriceWon: 120000,
      maxPriceWon: 300000,
      minEstimatedDays: 1,
      maxEstimatedDays: 2,
      categories: [
        "Static Website Development",
        "Dynamic Website Development",
        "CMS Development / Website Builder",
        "Website Maintenance",
      ],
    },

    {
      name: "Authentication System",
      koreanName: "회원가입/로그인",
      minPriceDollar: 1000,
      maxPriceDollar: 8000,
      minPriceWon: 1000000,
      maxPriceWon: 5000000,
      minEstimatedDays: 1,
      maxEstimatedDays: 3,
      categories: [
        "Dynamic Website Development",
        "E-Commerce Development",
        "Admin Dashboard",
        "Web Security",
      ],
    },
    {
      name: "JWT Authentication",
      koreanName: "JWT 인증",
      description: "Must be added with Authentification System",
      koreanDescription: "회원가입/로그인과 함께 추가해야함",
      minPriceDollar: 150,
      maxPriceDollar: 1000,
      minPriceWon: 150000,
      maxPriceWon: 1000000,
      minEstimatedDays: 1,
      maxEstimatedDays: 1,
      categories: [
        "Dynamic Website Development",
        "Admin Dashboard",
        "Web Security",
      ],
    },
    {
      name: "Social Authentication",
      koreanName: "소셜 로그인",
      description: "Must be added with Authentification System",
      koreanDescription: "회원가입/로그인과 함께 추가해야함",
      minPriceDollar: 100,
      maxPriceDollar: 300,
      minPriceWon: 100000,
      maxPriceWon: 300000,
      minEstimatedDays: 1,
      maxEstimatedDays: 1,
      categories: [
        "Dynamic Website Development",
        "E-Commerce Development",
        "Admin Dashboard",
        "Web Security",
      ]
    },
    {
      name: "Database Integration",
      koreanName: "데이터베이스 연동",
      minPriceDollar: 300,
      maxPriceDollar: 3000,
      minPriceWon: 300000,
      maxPriceWon: 3000000,
      minEstimatedDays: 1,
      maxEstimatedDays: 5,
      categories: [
        "Dynamic Website Development",
        "E-Commerce Development",
        "Admin Dashboard",
        "AI Integration",
      ],
    },
    {
      name: "API Development",
      koreanName: "API 개발",
      minPriceDollar: 200,
      maxPriceDollar: 2000,
      minPriceWon: 200000,
      maxPriceWon: 2000000,
      minEstimatedDays: 1,
      maxEstimatedDays: 2,
      categories: [
        "Dynamic Website Development",
        "E-Commerce Development",
        "Admin Dashboard",
        "Automation",
        "AI Integration",
      ],
    },
    {
      name: "Booking System",
      koreanName: "예약 시스템",
      minPriceDollar: 1000,
      maxPriceDollar: 10000,
      minPriceWon: 1000000,
      maxPriceWon: 10000000,
      minEstimatedDays: 3,
      maxEstimatedDays: 10,
      categories: [
        "Dynamic Website Development",
        "Admin Dashboard",
        "Automation",
      ],
    },
    {
      name: "Payment Integration",
      koreanName: "결제 시스템 연동",
      minPriceDollar: 2000,
      maxPriceDollar: 12000,
      minPriceWon: 1000000,
      maxPriceWon: 7000000,
      minEstimatedDays: 2,
      maxEstimatedDays: 7,
      categories: [
        "Dynamic Website Development",
        "E-Commerce Development",
        "Automation",
        "Web Security",
      ],
    },
    {
      name: "User Dashboard",
      koreanName: "사용자 대시보드",
      minPriceDollar: 2000,
      maxPriceDollar: 10000,
      minPriceWon: 2000000,
      maxPriceWon: 10000000,
      minEstimatedDays: 3,
      maxEstimatedDays: 14,
      categories: [
        "Dynamic Website Development",
        "Admin Dashboard",
        "E-Commerce Development",
      ],
    },
    {
      name: "Notification System",
      koreanName: "알림 시스템",
      minPriceDollar: 200,
      maxPriceDollar: 2000,
      minPriceWon: 200000,
      maxPriceWon: 2000000,
      minEstimatedDays: 1,
      maxEstimatedDays: 5,
      categories: [
        "Dynamic Website Development",
        "Admin Dashboard",
        "Automation",
        "E-Commerce Development",
      ],
    },

    {
      name: "Blog CMS",
      koreanName: "블로그 CMS",
      minPriceDollar: 500,
      maxPriceDollar: 5000,
      minPriceWon: 500000,
      maxPriceWon: 5000000,
      minEstimatedDays: 2,
      maxEstimatedDays: 5,
      categories: [
        "CMS Development / Website Builder",
        "SEO",
      ],
    },
    {
      name: "Content Management",
      koreanName: "콘텐츠 관리",
      minPriceDollar: 100,
      maxPriceDollar: 3000,
      minPriceWon: 100000,
      maxPriceWon: 3000000,
      minEstimatedDays: 1,
      maxEstimatedDays: 3,
      categories: [
        "CMS Development / Website Builder",
        "Admin Dashboard",
        "Website Maintenance",
      ],
    },
    {
      name: "Media Upload System",
      koreanName: "이미지 업로드 시스템",
      minPriceDollar: 100,
      maxPriceDollar: 1500,
      minPriceWon: 100000,
      maxPriceWon: 1000000,
      minEstimatedDays: 1,
      maxEstimatedDays: 1,
      categories: [
        "CMS Development / Website Builder",
        "Admin Dashboard",
        "E-Commerce Development",
      ],
    },
    {
      name: "SEO Controls",
      koreanName: "SEO 관리 기능",
      minPriceDollar: 300,
      maxPriceDollar: 2000,
      minPriceWon: 200000,
      maxPriceWon: 1500000,
      minEstimatedDays: 1,
      maxEstimatedDays: 1,
      categories: [
        "CMS Development / Website Builder",
        "SEO",
        "Admin Dashboard",
      ],
    },
    {
      name: "Rich Text Editor",
      koreanName: "리치 텍스트 에디터",
      minPriceDollar: 300,
      maxPriceDollar: 3000,
      minPriceWon: 300000,
      maxPriceWon: 3000000,
      minEstimatedDays: 1,
      maxEstimatedDays: 3,
      categories: [
        "CMS Development / Website Builder",
        "Admin Dashboard",
      ],
    },
    {
      name: "Role Permissions",
      koreanName: "권한 관리",
      minPriceDollar: 1000,
      maxPriceDollar: 5000,
      minPriceWon: 1000000,
      maxPriceWon: 5000000,
      minEstimatedDays: 1,
      maxEstimatedDays: 5,
      categories: [
        "CMS Development / Website Builder",
        "Admin Dashboard",
        "Web Security",
      ],
    },

    {
      name: "User Management",
      koreanName: "사용자 관리",
      minPriceDollar: 1000,
      maxPriceDollar: 7000,
      minPriceWon: 1000000,
      maxPriceWon: 7000000,
      minEstimatedDays: 1,
      maxEstimatedDays: 5,
      categories: [
        "Admin Dashboard",
        "Dynamic Website Development",
        "E-Commerce Development",
      ],
    },
    {
      name: "Order Management",
      koreanName: "주문 관리",
      minPriceDollar: 1500,
      maxPriceDollar: 12000,
      minPriceWon: 1000000,
      maxPriceWon: 12000000,
      minEstimatedDays: 2,
      maxEstimatedDays: 7,
      categories: [
        "Admin Dashboard",
        "E-Commerce Development",
      ],
    },
    {
      name: "Analytics Dashboard",
      koreanName: "통계 대시보드",
      minPriceDollar: 500,
      maxPriceDollar: 1500,
      minPriceWon: 500000,
      maxPriceWon: 15000000,
      minEstimatedDays: 2,
      maxEstimatedDays: 10,
      categories: [
        "Admin Dashboard",
        "Conversion",
        "E-Commerce Development",
      ],
    },
    {
      name: "Real-time Data",
      koreanName: "실시간 데이터",
      minPriceDollar: 1000,
      maxPriceDollar: 10000,
      minPriceWon: 1000000,
      maxPriceWon: 10000000,
      minEstimatedDays: 2,
      maxEstimatedDays: 7,
      categories: [
        "Admin Dashboard",
        "Dynamic Website Development",
        "E-Commerce Development",
      ],
    },

    {
      name: "CTA Optimization",
      koreanName: "CTA 최적화",
      minPriceDollar: 100,
      maxPriceDollar: 800,
      minPriceWon: 100000,
      maxPriceWon: 800000,
      minEstimatedDays: 1,
      maxEstimatedDays: 1,
      categories: [
        "Conversion",
        "Static Website Development",
        "E-Commerce Development",
        "Website Maintenance",
      ],
    },
    {
      name: "Funnel Design",
      koreanName: "퍼널 설계",
      minPriceDollar: 1000,
      maxPriceDollar: 10000,
      minPriceWon: 1000000,
      maxPriceWon: 10000000,
      minEstimatedDays: 1,
      maxEstimatedDays: 7,
      categories: [
        "Conversion",
        "Automation",
        "E-Commerce Development",
      ],
    },
    {
      name: "Heatmap Analysis",
      koreanName: "히트맵 분석",
      minPriceDollar: 300,
      maxPriceDollar: 2000,
      minPriceWon: 200000,
      maxPriceWon: 1500000,
      minEstimatedDays: 1,
      maxEstimatedDays: 1,
      categories: [
        "Conversion",
        "Speed Optimization",
      ],
    },
    {
      name: "A/B Testing",
      koreanName: "A/B 테스트",
      minPriceDollar: 2000,
      maxPriceDollar: 20000,
      minPriceWon: 1000000,
      maxPriceWon: 10000000,
      minEstimatedDays: 2,
      maxEstimatedDays: 10,
      categories: [
        "Conversion",
        "E-Commerce Development",
      ],
    },
    {
      name: "Conversion Tracking",
      koreanName: "전환 추적",
      minPriceDollar: 300,
      maxPriceDollar: 3000,
      minPriceWon: 200000,
      maxPriceWon: 2000000,
      minEstimatedDays: 1,
      maxEstimatedDays: 1,
      categories: [
        "Conversion",
        "SEO",
        "Automation",
        "E-Commerce Development",
      ],
    },

    {
      name: "Email Automation",
      koreanName: "이메일 자동화",
      minPriceDollar: 300,
      maxPriceDollar: 3000,
      minPriceWon: 300000,
      maxPriceWon: 3000000,
      minEstimatedDays: 1,
      maxEstimatedDays: 3,
      categories: [
        "Automation",
        "E-Commerce Development",
        "Website Maintenance",
      ],
    },
    {
      name: "Welcome Email",
      koreanName: "웰컴 이메일",
      minPriceDollar: 100,
      maxPriceDollar: 800,
      minPriceWon: 100000,
      maxPriceWon: 800000,
      minEstimatedDays: 1,
      maxEstimatedDays: 1,
      categories: [
        "Automation",
        "E-Commerce Development",
      ],
    },
    {
      name: "CRM Integration",
      koreanName: "CRM 연동",
      minPriceDollar: 2000,
      maxPriceDollar: 20000,
      minPriceWon: 1000000,
      maxPriceWon: 10000000,
      minEstimatedDays: 2,
      maxEstimatedDays: 10,
      categories: [
        "Automation",
        "Dynamic Website Development",
        "E-Commerce Development",
      ],
    },
    {
      name: "Quote Automation",
      koreanName: "견적 자동화",
      minPriceDollar: 1000,
      maxPriceDollar: 10000,
      minPriceWon: 1000000,
      maxPriceWon: 7000000,
      minEstimatedDays: 1,
      maxEstimatedDays: 5,
      categories: [
        "Automation",
        "Dynamic Website Development",
        "AI Integration",
      ],
    },
    {
      name: "Booking Automation",
      koreanName: "예약 자동화",
      minPriceDollar: 1000,
      maxPriceDollar: 15000,
      minPriceWon: 1000000,
      maxPriceWon: 7000000,
      minEstimatedDays: 2,
      maxEstimatedDays: 7,
      categories: [
        "Automation",
        "Dynamic Website Development",
      ],
    },
    {
      name: "Slack Notifications",
      koreanName: "Slack 알림 시스템",
      minPriceDollar: 300,
      maxPriceDollar: 2000,
      minPriceWon: 200000,
      maxPriceWon: 1500000,
      minEstimatedDays: 1,
      maxEstimatedDays: 1,
      categories: [
        "Automation",
        "Admin Dashboard",
        "DevOps Services & Cloud Infrastructure",
      ],
    },

    {
      name: "Logo Design",
      koreanName: "로고 디자인",
      minPriceDollar: 150,
      maxPriceDollar: 300,
      minPriceWon: 150000,
      maxPriceWon: 300000,
      minEstimatedDays: 2,
      maxEstimatedDays: 7,
      categories: [
        "Branding & UI/UX",
      ],
    },
    {
      name: "Color System",
      koreanName: "컬러 시스템",
      minPriceDollar: 100,
      minPriceWon: 100000,
      minEstimatedDays: 1,
      maxEstimatedDays: 3,
      categories: [
        "Branding & UI/UX",
        "Static Website Development",
        "Dynamic Website Development",
      ],
    },
    {
      name: "UI Design",
      koreanName: "UI 디자인",
      minPriceDollar: 200,
      maxPriceDollar: 2000,
      minPriceWon: 200000,
      maxPriceWon: 1500000,
      minEstimatedDays: 1,
      maxEstimatedDays: 2,
      categories: [
        "Branding & UI/UX",
        "Static Website Development",
        "Dynamic Website Development",
        "Admin Dashboard",
        "E-Commerce Development",
      ],
    },
    {
      name: "Design System",
      koreanName: "디자인 시스템",
      minPriceDollar: 500,
      maxPriceDollar: 1500,
      minPriceWon: 500000,
      maxPriceWon: 1500000,
      minEstimatedDays: 3,
      maxEstimatedDays: 14,
      categories: [
        "Branding & UI/UX",
        "Admin Dashboard",
        "Dynamic Website Development",
      ],
    },
    {
      name: "Brand Guidelines",
      koreanName: "브랜드 가이드",
      minPriceDollar: 300,
      maxPriceDollar: 1000,
      minPriceWon: 300000,
      maxPriceWon: 1000000,
      minEstimatedDays: 2,
      maxEstimatedDays: 10,
      categories: [
        "Branding & UI/UX",
      ],
    },

    {
      name: "Image Optimization",
      koreanName: "이미지 최적화",
      minPriceDollar: 100,
      maxPriceDollar: 800,
      minPriceWon: 100000,
      maxPriceWon: 800000,
      minEstimatedDays: 1,
      maxEstimatedDays: 1,
      categories: [
        "Speed Optimization",
        "Static Website Development",
        "E-Commerce Development",
        "Website Maintenance",
      ],
    },
    {
      name: "Lazy Loading",
      koreanName: "Lazy Loading",
      minPriceDollar: 100,
      maxPriceDollar: 800,
      minPriceWon: 100000,
      maxPriceWon: 800000,
      minEstimatedDays: 1,
      maxEstimatedDays: 1,
      categories: [
        "Speed Optimization",
        "Static Website Development",
        "Dynamic Website Development",
        "E-Commerce Development",
      ],
    },
    {
      name: "Lighthouse Optimization",
      koreanName: "Lighthouse 개선",
      minPriceDollar: 500,
      maxPriceDollar: 3000,
      minPriceWon: 500000,
      maxPriceWon: 3000000,
      minEstimatedDays: 1,
      maxEstimatedDays: 5,
      categories: [
        "Speed Optimization",
        "SEO",
        "Conversion",
      ],
    },
    {
      name: "Core Web Vitals",
      koreanName: "Core Web Vitals 개선",
      minPriceDollar: 1000,
      maxPriceDollar: 7000,
      minPriceWon: 1000000,
      maxPriceWon: 7000000,
      minEstimatedDays: 1,
      maxEstimatedDays: 7,
      categories: [
        "Speed Optimization",
        "SEO",
        "Conversion",
      ],
    },
    {
      name: "Caching Optimization",
      koreanName: "캐싱 최적화",
      minPriceDollar: 500,
      maxPriceDollar: 3000,
      minPriceWon: 500000,
      maxPriceWon: 3000000,
      minEstimatedDays: 1,
      maxEstimatedDays: 5,
      categories: [
        "Speed Optimization",
        "DevOps Services & Cloud Infrastructure",
      ],
    },

    {
      name: "Metadata Optimization",
      koreanName: "메타 태그 최적화",
      minPriceDollar: 100,
      maxPriceDollar: 500,
      minPriceWon: 100000,
      maxPriceWon: 500000,
      minEstimatedDays: 1,
      maxEstimatedDays: 1,
      categories: [
        "SEO",
        "Static Website Development",
        "CMS Development / Website Builder",
        "E-Commerce Development",
      ],
    },
    {
      name: "Sitemap Setup",
      koreanName: "Sitemap 설정",
      minPriceDollar: 50,
      maxPriceDollar: 200,
      minPriceWon: 50000,
      maxPriceWon: 200000,
      minEstimatedDays: 1,
      maxEstimatedDays: 1,
      categories: [
        "SEO",
        "Static Website Development",
        "Dynamic Website Development",
        "E-Commerce Development",
      ],
    },
    {
      name: "Robots.txt Setup",
      koreanName: "robots.txt 설정",
      minPriceDollar: 30,
      maxPriceDollar: 100,
      minPriceWon: 30000,
      maxPriceWon: 100000,
      minEstimatedDays: 1,
      maxEstimatedDays: 1,
      categories: [
        "SEO",
        "Static Website Development",
        "Dynamic Website Development",
      ],
    },
    {
      name: "Technical SEO",
      koreanName: "Technical SEO",
      minPriceDollar: 500,
      maxPriceDollar: 2000,
      minPriceWon: 500000,
      maxPriceWon: 2000000,
      minEstimatedDays: 1,
      maxEstimatedDays: 7,
      categories: [
        "SEO",
        "Speed Optimization",
        "E-Commerce Development",
      ],
    },
    {
      name: "Keyword Optimization",
      koreanName: "키워드 최적화",
      minPriceDollar: 500,
      maxPriceDollar: 2000,
      minPriceWon: 500000,
      maxPriceWon: 2000000,
      minEstimatedDays: 1,
      maxEstimatedDays: 5,
      categories: [
        "SEO",
        "Conversion",
      ],
    },

    {
      name: "AI Chatbot",
      koreanName: "AI 챗봇",
      minPriceDollar: 1000,
      maxPriceDollar: 10000,
      minPriceWon: 1000000,
      maxPriceWon: 10000000,
      minEstimatedDays: 3,
      maxEstimatedDays: 14,
      categories: [
        "AI Integration",
        "Automation",
        "Dynamic Website Development",
        "E-Commerce Development",
      ],
    },
    {
      name: "AI Search",
      koreanName: "AI 검색",
      minPriceDollar: 1000,
      maxPriceDollar: 10000,
      minPriceWon: 1000000,
      maxPriceWon: 10000000,
      minEstimatedDays: 3,
      maxEstimatedDays: 14,
      categories: [
        "AI Integration",
        "Dynamic Website Development",
        "E-Commerce Development",
      ],
    },
    {
      name: "Recommendation System",
      koreanName: "추천 시스템",
      minPriceDollar: 1000,
      maxPriceDollar: 10000,
      minPriceWon: 1000000,
      maxPriceWon: 10000000,
      minEstimatedDays: 7,
      maxEstimatedDays: 28,
      categories: [
        "AI Integration",
        "E-Commerce Development",
      ],
    },
    {
      name: "AI Content Generation",
      koreanName: "AI 콘텐츠 생성",
      minPriceDollar: 1000,
      maxPriceDollar: 10000,
      minPriceWon: 1000000,
      maxPriceWon: 10000000,
      minEstimatedDays: 2,
      maxEstimatedDays: 10,
      categories: [
        "AI Integration",
        "CMS Development / Website Builder",
        "Automation",
      ],
    },
    {
      name: "AI Quote Generator",
      koreanName: "AI 견적 생성",
      minPriceDollar: 1000,
      maxPriceDollar: 10000,
      minPriceWon: 1000000,
      maxPriceWon: 10000000,
      minEstimatedDays: 2,
      maxEstimatedDays: 10,
      categories: [
        "AI Integration",
        "Automation",
        "Dynamic Website Development",
      ],
    },

    {
      name: "AWS Deployment",
      koreanName: "AWS 배포",
      minPriceDollar: 1000,
      maxPriceDollar: 5000,
      minPriceWon: 1000000,
      maxPriceWon: 5000000,
      minEstimatedDays: 1,
      maxEstimatedDays: 5,
      categories: [
        "DevOps Services & Cloud Infrastructure",
        "Dynamic Website Development",
        "E-Commerce Development",
        "Website Maintenance",
      ],
    },
    {
      name: "Docker Setup",
      koreanName: "Docker 구성",
      minPriceDollar: 500,
      maxPriceDollar: 3000,
      minPriceWon: 500000,
      maxPriceWon: 3000000,
      minEstimatedDays: 1,
      maxEstimatedDays: 5,
      categories: [
        "DevOps Services & Cloud Infrastructure",
      ],
    },
    {
      name: "CI/CD Pipeline",
      koreanName: "CI/CD 구축",
      minPriceDollar: 500,
      maxPriceDollar: 10000,
      minPriceWon: 500000,
      maxPriceWon: 10000000,
      minEstimatedDays: 2,
      maxEstimatedDays: 10,
      categories: [
        "DevOps Services & Cloud Infrastructure",
      ],
    },
    {
      name: "Monitoring Setup",
      koreanName: "모니터링 시스템",
      minPriceDollar: 500,
      maxPriceDollar: 5000,
      minPriceWon: 500000,
      maxPriceWon: 5000000,
      minEstimatedDays: 1,
      maxEstimatedDays: 5,
      categories: [
        "DevOps Services & Cloud Infrastructure",
        "Website Maintenance",
        "Web Security",
      ],
    },
    {
      name: "Auto Scaling",
      koreanName: "Auto Scaling",
      minPriceDollar: 1000,
      maxPriceDollar: 1500,
      minPriceWon: 1000000,
      maxPriceWon: 15000000,
      minEstimatedDays: 2,
      maxEstimatedDays: 10,
      categories: [
        "DevOps Services & Cloud Infrastructure",
        "Speed Optimization",
      ],
    },

    {
      name: "SSL Setup",
      koreanName: "SSL 설정",
      minPriceDollar: 50,
      maxPriceDollar: 200,
      minPriceWon: 50000,
      maxPriceWon: 200000,
      minEstimatedDays: 1,
      maxEstimatedDays: 1,
      categories: [
        "Web Security",
        "DevOps Services & Cloud Infrastructure",
        "Website Maintenance",
      ],
    },
    {
      name: "Security Headers",
      koreanName: "보안 헤더",
      minPriceDollar: 100,
      maxPriceDollar: 500,
      minPriceWon: 100000,
      maxPriceWon: 500000,
      minEstimatedDays: 1,
      maxEstimatedDays: 1,
      categories: [
        "Web Security",
        "Dynamic Website Development",
      ],
    },
    {
      name: "Rate Limiting",
      koreanName: "요청 제한 시스템",
      minPriceDollar: 200,
      maxPriceDollar: 1500,
      minPriceWon: 200000,
      maxPriceWon: 1500000,
      minEstimatedDays: 1,
      maxEstimatedDays: 1,
      categories: [
        "Web Security",
        "Dynamic Website Development",
        "AI Integration",
      ],
    },
    {
      name: "Authentication Security",
      koreanName: "인증 보안",
      minPriceDollar: 1000,
      maxPriceDollar: 7000,
      minPriceWon: 500000,
      maxPriceWon: 7000000,
      minEstimatedDays: 1,
      maxEstimatedDays: 5,
      categories: [
        "Web Security",
        "Dynamic Website Development",
        "Admin Dashboard",
      ],
    },
    {
      name: "Vulnerability Scanning",
      koreanName: "취약점 점검",
      minPriceDollar: 1000,
      maxPriceDollar: 10000,
      minPriceWon: 1000000,
      maxPriceWon: 10000000,
      minEstimatedDays: 1,
      maxEstimatedDays: 7,
      categories: [
        "Web Security",
        "DevOps Services & Cloud Infrastructure",
        "Website Maintenance",
      ],
    },

    {
      name: "Text Updates",
      koreanName: "텍스트 수정",
      minPriceDollar: 30,
      maxPriceDollar: 100,
      minPriceWon: 30000,
      maxPriceWon: 100000,
      minEstimatedDays: 1,
      maxEstimatedDays: 1,
      categories: [
        "Website Maintenance",
      ],
    },
    {
      name: "Image Replacement",
      koreanName: "이미지 교체",
      minPriceDollar: 50,
      maxPriceDollar: 150,
      minPriceWon: 50000,
      maxPriceWon: 150000,
      minEstimatedDays: 1,
      maxEstimatedDays: 1,
      categories: [
        "Website Maintenance",
      ],
    },
    {
      name: "Bug Fixes",
      koreanName: "버그 수정",
      minPriceDollar: 100,
      maxPriceDollar: 1000,
      minPriceWon: 100000,
      maxPriceWon: 1000000,
      minEstimatedDays: 1,
      maxEstimatedDays: 1,
      categories: [
        "Website Maintenance",
        "Web Security",
      ],
    },
    {
      name: "Feature Updates",
      koreanName: "기능 수정",
      minPriceDollar: 200,
      maxPriceDollar: 3000,
      minPriceWon: 200000,
      maxPriceWon: 3000000,
      minEstimatedDays: 1,
      maxEstimatedDays: 3,
      categories: [
        "Website Maintenance",
        "Dynamic Website Development",
      ],
    },

    {
      name: "Query Optimization",
      koreanName: "쿼리 최적화",
      minPriceDollar: 200,
      maxPriceDollar: 2000,
      minPriceWon: 200000,
      maxPriceWon: 2000000,
      minEstimatedDays: 1,
      maxEstimatedDays: 2,
      categories: [
        "Speed Optimization",
        "Dynamic Website Development",
        "E-Commerce Development",
        "Admin Dashboard",
      ],
    },
    {
      name: "Database Indexing",
      koreanName: "데이터베이스 인덱싱",
      minPriceDollar: 200,
      maxPriceDollar: 1500,
      minPriceWon: 100000,
      maxPriceWon: 1000000,
      minEstimatedDays: 1,
      maxEstimatedDays: 1,
      categories: [
        "Speed Optimization",
        "Dynamic Website Development",
        "E-Commerce Development",
        "Admin Dashboard",
      ],
    },
    {
      name: "N+1 Query Prevention",
      koreanName: "N+1 문제 해결",
      minPriceDollar: 200,
      maxPriceDollar: 3000,
      minPriceWon: 200000,
      maxPriceWon: 3000000,
      minEstimatedDays: 1,
      maxEstimatedDays: 2,
      categories: [
        "Speed Optimization",
        "Dynamic Website Development",
        "E-Commerce Development",
        "Admin Dashboard",
      ],
    },
    {
      name: "API Optimization",
      koreanName: "API 성능 개선",
      minPriceDollar: 500,
      maxPriceDollar: 3000,
      minPriceWon: 500000,
      maxPriceWon: 3000000,
      minEstimatedDays: 1,
      maxEstimatedDays: 5,
      categories: [
        "Speed Optimization",
        "Dynamic Website Development",
        "E-Commerce Development",
      ],
    },
    {
      name: "Redis Caching",
      koreanName: "Redis 캐싱",
      minPriceDollar: 500,
      maxPriceDollar: 4000,
      minPriceWon: 500000,
      maxPriceWon: 4000000,
      minEstimatedDays: 1,
      maxEstimatedDays: 5,
      categories: [
        "Speed Optimization",
        "Dynamic Website Development",
        "E-Commerce Development",
        "DevOps Services & Cloud Infrastructure",
      ],
    },
    {
      name: "Slow Query Analysis",
      koreanName: "느린 쿼리 분석",
      minPriceDollar: 100,
      maxPriceDollar: 1000,
      minPriceWon: 100000,
      maxPriceWon: 1000000,
      minEstimatedDays: 1,
      maxEstimatedDays: 1,
      categories: [
        "Speed Optimization",
        "Admin Dashboard",
        "Website Maintenance",
      ],
    },

    {
      name: "Product Management",
      koreanName: "상품 관리 시스템",
      minPriceDollar: 2000,
      maxPriceDollar: 10000,
      minPriceWon: 1000000,
      maxPriceWon: 7000000,
      minEstimatedDays: 1,
      maxEstimatedDays: 5,
      categories: [
        "E-Commerce Development",
        "Admin Dashboard",
        "CMS Development / Website Builder",
      ],
    },
    {
      name: "Shopping Cart",
      koreanName: "장바구니",
      minPriceDollar: 1000,
      maxPriceDollar: 8000,
      minPriceWon: 500000,
      maxPriceWon: 5000000,
      minEstimatedDays: 1,
      maxEstimatedDays: 5,
      categories: [
        "E-Commerce Development",
      ],
    },
    {
      name: "Inventory Management",
      koreanName: "재고 관리",
      minPriceDollar: 2000,
      maxPriceDollar: 10000,
      minPriceWon: 1000000,
      maxPriceWon: 7000000,
      minEstimatedDays: 1,
      maxEstimatedDays: 7,
      categories: [
        "E-Commerce Development",
        "Admin Dashboard",
      ],
    },
    {
      name: "Customer Accounts",
      koreanName: "고객 계정 시스템",
      minPriceDollar: 2000,
      maxPriceDollar: 8000,
      minPriceWon: 1000000,
      maxPriceWon: 5000000,
      minEstimatedDays: 1,
      maxEstimatedDays: 5,
      categories: [
        "E-Commerce Development",
        "Dynamic Website Development",
      ],
    },
    {
      name: "Subscription Payments",
      koreanName: "구독 결제",
      minPriceDollar: 3000,
      maxPriceDollar: 25000,
      minPriceWon: 2000000,
      maxPriceWon: 15000000,
      minEstimatedDays: 2,
      maxEstimatedDays: 10,
      categories: [
        "E-Commerce Development",
        "Automation",
        "Dynamic Website Development",
      ],
    },
    {
      name: "Shipping Integration",
      koreanName: "배송 시스템 연동",
      minPriceDollar: 2000,
      maxPriceDollar: 10000,
      minPriceWon: 1000000,
      maxPriceWon: 7000000,
      minEstimatedDays: 1,
      maxEstimatedDays: 5,
      categories: [
        "E-Commerce Development",
        "Automation",
      ],
    },
    {
      name: "Sales Analytics Dashboard",
      koreanName: "판매 분석 대시보드",
      minPriceDollar: 3000,
      maxPriceDollar: 20000,
      minPriceWon: 1500000,
      maxPriceWon: 10000000,
      minEstimatedDays: 2,
      maxEstimatedDays: 10,
      categories: [
        "E-Commerce Development",
        "Admin Dashboard",
        "Conversion",
      ],
    },
    {
      name: "AI Recommendations",
      koreanName: "AI 상품 추천",
      minPriceDollar: 1000,
      maxPriceDollar: 10000,
      minPriceWon: 1000000,
      maxPriceWon: 10000000,
      minEstimatedDays: 7,
      maxEstimatedDays: 28,
      categories: [
        "E-Commerce Development",
        "AI Integration",
      ],
    },
  ];

  for (const feature of features) {
    const { categories, ...data } = feature;

      await prisma.feature.upsert({
          // Finds existing feature by unique name
          where: {
              name: data.name,
          },

          // Updates existing feature
          update: {
              ...data,
              categories: {
                  set: categories.map((categoryName) => ({
                      name: categoryName,
                  })),
              },
          },

          // Creates feature if it does not exist
          create: {
              ...data,
              categories: {
                  connect: categories.map((categoryName) => ({
                      name: categoryName,
                  })),
              },
          },
      });
  }

  console.log("Features seeded.");
}

module.exports = {
  seedFeatures,
};