async function seedPackages(prisma) {
  const packages = [
    {
      name: "My Website Is Slow Package",
      koreanName: "웹사이트가 느려요 패키지",
      description: "Website performance and database optimization package.",
      koreanDescription: "웹사이트 속도 및 데이터베이스 최적화 패키지.",
      minPriceDollar: 6000,
      maxPriceDollar: 15000,
      minPriceWon: 3500000,
      maxPriceWon: 8000000,
      features: [
        "Image Optimization",
        "Lazy Loading",
        "Lighthouse Optimization",
        "Core Web Vitals",
        "Caching Optimization",
        "Query Optimization",
        "Database Indexing",
        "Slow Query Analysis",
        "Redis Caching",
        "API Optimization",
      ],
    },

    {
      name: "Login Website Starter",
      koreanName: "로그인 포함 웹사이트",
      description: "Website package with authentication system.",
      koreanDescription: "로그인 기능이 포함된 웹사이트 패키지.",
      minPriceDollar: 12000,
      maxPriceDollar: 30000,
      minPriceWon: 6000000,
      maxPriceWon: 15000000,
      features: [
        "Responsive Design",
        "Mobile Optimization",
        "Authentication System",
        "JWT Authentication",
        "Database Integration",
        "User Dashboard",
        "Authentication Security",
        "Security Headers",
      ],
    },

    {
      name: "Login + Payment Website",
      koreanName: "로그인 + 결제 웹사이트",
      description: "Website with authentication and payment systems.",
      koreanDescription: "로그인 및 결제 시스템이 포함된 웹사이트.",
      minPriceDollar: 18000,
      maxPriceDollar: 45000,
      minPriceWon: 9000000,
      maxPriceWon: 25000000,
      features: [
        "Authentication System",
        "JWT Authentication",
        "Database Integration",
        "Payment Integration",
        "User Dashboard",
        "Email Automation",
        "SSL Setup",
        "Authentication Security",
      ],
    },

    {
      name: "Payment Website",
      koreanName: "결제 웹사이트",
      description: "Simple payment-based business website.",
      koreanDescription: "결제 기능이 포함된 비즈니스 웹사이트.",
      minPriceDollar: 5000,
      maxPriceDollar: 18000,
      minPriceWon: 3000000,
      maxPriceWon: 10000000,
      features: [
        "Responsive Design",
        "Mobile Optimization",
        "Payment Integration",
        "Contact Form",
        "Email Automation",
        "SSL Setup",
        "Metadata Optimization",
      ],
    },

    {
      name: "Smart Quote Website",
      koreanName: "견적 자동화 사이트",
      description: "Automatic quote calculation website.",
      koreanDescription: "자동 견적 계산 웹사이트.",
      minPriceDollar: 8000,
      maxPriceDollar: 25000,
      minPriceWon: 5000000,
      maxPriceWon: 15000000,
      features: [
        "Quote Automation",
        "API Development",
        "Database Integration",
        "Contact Form",
        "Email Automation",
        "Conversion Tracking",
        "Analytics Dashboard",
      ],
    },

    {
      name: "Digital Business Card Website",
      koreanName: "명함 사이트",
      description: "Simple business card and contact website.",
      koreanDescription: "간단한 명함형 웹사이트.",
      minPriceDollar: 1500,
      maxPriceDollar: 5000,
      minPriceWon: 900000,
      maxPriceWon: 2500000,
      features: [
        "Responsive Design",
        "Mobile Optimization",
        "Contact Form",
        "Metadata Optimization",
        "Hosting Deployment",
      ],
    },

    {
      name: "Showroom Website",
      koreanName: "쇼룸 사이트",
      description: "Product showcase website without payment.",
      koreanDescription: "결제 없는 상품 전시 사이트.",
      minPriceDollar: 5000,
      maxPriceDollar: 15000,
      minPriceWon: 3000000,
      maxPriceWon: 9000000,
      features: [
        "Responsive Design",
        "Mobile Optimization",
        "Product Management",
        "Media Upload System",
        "Image Optimization",
        "Contact Form",
        "Metadata Optimization",
      ],
    },

    {
      name: "Portfolio Website",
      koreanName: "포트폴리오 사이트",
      description: "Portfolio website for creators and developers.",
      koreanDescription: "개발자 및 크리에이터용 포트폴리오 사이트.",
      minPriceDollar: 2500,
      maxPriceDollar: 8000,
      minPriceWon: 1500000,
      maxPriceWon: 5000000,
      features: [
        "Responsive Design",
        "Mobile Optimization",
        "Page Animation",
        "Additional Pages",
        "Contact Form",
        "Color System",
      ],
    },

    {
      name: "Rank Up & Monthly Report Package",
      koreanName: "SEO + 리포트 패키지",
      description: "SEO optimization and analytics reporting package.",
      koreanDescription: "SEO 최적화 및 분석 리포트 패키지.",
      minPriceDollar: 6000,
      maxPriceDollar: 20000,
      minPriceWon: 3000000,
      maxPriceWon: 10000000,
      features: [
        "Metadata Optimization",
        "Sitemap Setup",
        "Robots.txt Setup",
        "Technical SEO",
        "Keyword Optimization",
        "Conversion Tracking",
        "Analytics Dashboard",
        "Heatmap Analysis",
      ],
    },

    {
      name: "AI Add-On Package",
      koreanName: "AI 기능 추가 패키지",
      description: "AI-powered feature integration package.",
      koreanDescription: "AI 기능 추가 패키지.",
      minPriceDollar: 10000,
      maxPriceDollar: 35000,
      minPriceWon: 6000000,
      maxPriceWon: 20000000,
      features: [
        "AI Chatbot",
        "AI Content Generation",
        "AI Quote Generator",
        "AI Search",
        "API Development",
        "Rate Limiting",
        "Database Integration",
      ],
    },

    {
      name: "Social Login + Auth Package",
      koreanName: "소셜 로그인 + 로그인 패키지",
      description: "Authentication package with social login.",
      koreanDescription: "소셜 로그인 포함 인증 패키지.",
      minPriceDollar: 8000,
      maxPriceDollar: 20000,
      minPriceWon: 5000000,
      maxPriceWon: 12000000,
      features: [
        "Authentication System",
        "JWT Authentication",
        "Social Authentication",
        "Database Integration",
        "Authentication Security",
        "User Management",
      ],
    },

    {
      name: "Location & Map Website",
      koreanName: "지도 위치 사이트",
      description: "Business location and map integration website.",
      koreanDescription: "지도 및 위치 안내 웹사이트.",
      minPriceDollar: 2500,
      maxPriceDollar: 8000,
      minPriceWon: 1500000,
      maxPriceWon: 5000000,
      features: [
        "Responsive Design",
        "Mobile Optimization",
        "Contact Form",
        "Additional Pages",
        "Metadata Optimization",
      ],
    },

    {
      name: "Custom Idea Builder Package",
      koreanName: "특수 기능 구현 패키지",
      description: "Custom feature and idea implementation package.",
      koreanDescription: "특수 기능 및 아이디어 구현 패키지.",
      minPriceDollar: 5000,
      maxPriceDollar: 30000,
      minPriceWon: 3000000,
      maxPriceWon: 15000000,
      features: [
        "API Development",
        "Database Integration",
        "Notification System",
        "Slack Notifications",
        "Page Animation",
        "Feature Updates",
      ],
    },

    {
      name: "Online Store Starter",
      koreanName: "기본 쇼핑몰 패키지",
      description: "Starter e-commerce website package.",
      koreanDescription: "기본 쇼핑몰 구축 패키지.",
      minPriceDollar: 12000,
      maxPriceDollar: 35000,
      minPriceWon: 7000000,
      maxPriceWon: 20000000,
      features: [
        "Product Management",
        "Shopping Cart",
        "Payment Integration",
        "Customer Accounts",
        "Order Management",
        "Mobile Optimization",
        "Metadata Optimization",
        "SSL Setup",
      ],
    },

    {
      name: "Growth E-Commerce Package",
      koreanName: "성장형 쇼핑몰 패키지",
      description: "Growth-focused e-commerce package.",
      koreanDescription: "고급 기능이 포함된 성장형 쇼핑몰 패키지.",
      minPriceDollar: 25000,
      maxPriceDollar: 80000,
      minPriceWon: 15000000,
      maxPriceWon: 50000000,
      features: [
        "Product Management",
        "Shopping Cart",
        "Payment Integration",
        "Order Management",
        "Inventory Management",
        "Customer Accounts",
        "Shipping Integration",
        "Sales Analytics Dashboard",
        "Email Automation",
        "Conversion Tracking",
        "Technical SEO",
      ],
    },

    {
      name: "Subscription Business Website",
      koreanName: "구독 결제 사이트",
      description: "Subscription-based business website.",
      koreanDescription: "구독 결제 기반 웹사이트.",
      minPriceDollar: 20000,
      maxPriceDollar: 60000,
      minPriceWon: 12000000,
      maxPriceWon: 35000000,
      features: [
        "Authentication System",
        "Customer Accounts",
        "Subscription Payments",
        "Payment Integration",
        "Email Automation",
        "User Dashboard",
        "Authentication Security",
      ],
    },

    {
      name: "Admin Control Center Package",
      koreanName: "관리자 시스템 패키지",
      description: "Advanced admin dashboard package.",
      koreanDescription: "고급 관리자 시스템 구축 패키지.",
      minPriceDollar: 18000,
      maxPriceDollar: 50000,
      minPriceWon: 9000000,
      maxPriceWon: 30000000,
      features: [
        "Analytics Dashboard",
        "User Management",
        "Role Permissions",
        "Content Management",
        "Real-time Data",
        "Notification System",
      ],
    },

    {
      name: "Website Care Plan",
      koreanName: "웹사이트 유지보수 패키지",
      description: "Monthly website maintenance and support package.",
      koreanDescription: "웹사이트 유지보수 및 관리 패키지.",
      minPriceDollar: 500,
      maxPriceDollar: 12000,
      minPriceWon: 300000,
      maxPriceWon: 7000000,
      features: [
        "Text Updates",
        "Image Replacement",
        "Bug Fixes",
        "Feature Updates",
        "SSL Setup",
        "Monitoring Setup",
        "Vulnerability Scanning",
      ],
    },

    {
      name: "Fast Launch Website Builder Package",
      koreanName: "빠른 런칭 웹사이트 빌더 패키지",
      description: "Fast-launch builder-based website package.",
      koreanDescription: "웹사이트 빌더 기반 빠른 구축 패키지.",
      minPriceDollar: 1000,
      maxPriceDollar: 20000,
      minPriceWon: 800000,
      maxPriceWon: 10000000,
      features: [
        "Responsive Design",
        "Mobile Optimization",
        "Contact Form",
        "Metadata Optimization",
        "Hosting Deployment",
        "Additional Pages",
        "Multi-language Support",
        "Blog CMS",
        "Booking System",
      ],
    },

    {
      name: "Website Builder E-Commerce Package",
      koreanName: "웹사이트 빌더 쇼핑몰 패키지",
      description: "Builder-based e-commerce website package.",
      koreanDescription: "웹사이트 빌더 기반 쇼핑몰 패키지.",
      minPriceDollar: 3000,
      maxPriceDollar: 80000,
      minPriceWon: 2000000,
      maxPriceWon: 50000000,
      features: [
        "Product Management",
        "Shopping Cart",
        "Payment Integration",
        "Customer Accounts",
        "Order Management",
        "Mobile Optimization",
        "Metadata Optimization",
        "Email Automation",
        "Analytics Dashboard",
        "Shipping Integration",
      ],
    },
  ];

  for (const pkg of packages) {
    const { features, ...data } = pkg;

    await prisma.package.create({
      data: {
        ...data,
        features: {
          connect: features.map((name) => ({ name })),
        },
      },
    });
  }

  console.log("Packages seeded.");
}

module.exports = {
  seedPackages,
};